import localFont from "next/font/local";
import "./globals.css";
import dynamic from "next/dynamic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const Wallet = dynamic(
  () => import("@/solana/wallet-provider").then((mod) => mod.Wallet),
  { ssr: false }
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Wallet>{children}</Wallet>
      </body>
    </html>
  );
}
